-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 15:11:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Store` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `Store` ;

-- -----------------------------------------------------
-- Table `Store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`users`(
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `login` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `password_hash` BINARY(64) NOT NULL,
  `salt` BINARY(16) NOT NULL,
  `role` ENUM('ADMIN', 'MANAGER', 'CLIENT') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_cs_0900_ai_ci' NOT NULL,
  `status` ENUM('NOT_CONFIRMED, CONFIRMED, DELETED') NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idusers_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`devices` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `price` DECIMAL NOT NULL,
  `picture_path` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `type` ENUM('HARD_DISK', 'HULL', 'KEYBOARD', 'MONITOR', 'MOUSE', 'POWER_SUPPLY', 'PROCESSOR', 'RAM', 'SPEAKER', 'VIDEOCARD', 'COOLER', 'VENTILATOR', 'MOTHER_DOARD') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`device_id`),
  UNIQUE INDEX `processor_id_UNIQUE` (`device_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_status` ENUM('ORDERED', 'IN_PROGRESS', 'COMPLETED') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT 'ORDERED',
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_orders_users_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `Store`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store`.`devices_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store`.`devices_has_orders` (
  `id_device` INT NOT NULL,
  `id_order` INT NOT NULL,
  `number` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_device`, `id_order`),
  INDEX `fk_devices_has_orders_orders_idx` (`id_order` ASC) VISIBLE,
  INDEX `fk_devices_has_orders_devices_idx` (`id_device` ASC) VISIBLE,
  CONSTRAINT `fk_devices_has_orders_devices`
    FOREIGN KEY (`id_device`)
    REFERENCES `Store`.`devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devices_has_orders_orders`
    FOREIGN KEY (`id_order`)
    REFERENCES `Store`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
